version: '2'
services:

  web:
    image: mfrellum/learninglocker:1.14.0-http
    build: .
    links:
      - db:mongo
    environment:
      LEARNINGLOCKER_DB_HOST: 'mongo:27017' # Have to set this for now because of change to version 2 of docker-compose file
      APP_URL: 'lrs.dockerhost' # Map in /etc/hosts on docker-host
      APP_SECRET_KEY: 'CHANGEME12345678'
      SMTP_SERVER: 'smtp.sendgrid.net'
      SMTP_PORT: 587
      SMTP_USER: 'your own'
      SMTP_PASSWORD: 'your own'
      EMAIL_FROM_NAME: 'Learning Locker LRS Docker Container'
      EMAIL_FROM_ADDRESS: 'learninglocker@lrs.localhost'
    ports:
      - "9980:80"
  db:
    image: tutum/mongodb:3.2
    environment:
      MONGODB_DATABASE: 'learninglocker'
      MONGODB_USER: 'learninglocker'
      MONGODB_PASS: 'learninglocker'
    ports:
      - "27017:27017"
      - "28017:28017"
